import { db } from './client'
import { products } from './schema'
import { generateId, now } from './utils'

const SEED_PRODUCTS = [
  {
    name: 'Куриная грудка (варёная)',
    brand: null,
    kcalPer100g: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 74,
  },
  {
    name: 'Куриное бедро (жареное)',
    brand: null,
    kcalPer100g: 209,
    protein: 26,
    fat: 10.9,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 84,
  },
  {
    name: 'Говядина (варёная)',
    brand: null,
    kcalPer100g: 218,
    protein: 26.8,
    fat: 12,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 60,
  },
  {
    name: 'Лосось (запечённый)',
    brand: null,
    kcalPer100g: 206,
    protein: 20,
    fat: 13,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 59,
  },
  {
    name: 'Тунец (консерва в воде)',
    brand: null,
    kcalPer100g: 116,
    protein: 26,
    fat: 1,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 333,
  },
  {
    name: 'Яйцо куриное',
    brand: null,
    kcalPer100g: 155,
    protein: 12.6,
    fat: 10.6,
    carbs: 1.1,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
  },
  {
    name: 'Творог 5%',
    brand: null,
    kcalPer100g: 121,
    protein: 17,
    fat: 5,
    carbs: 3,
    fiber: 0,
    sugar: 3,
    sodium: 44,
  },
  {
    name: 'Творог 0%',
    brand: null,
    kcalPer100g: 71,
    protein: 18,
    fat: 0.6,
    carbs: 1.8,
    fiber: 0,
    sugar: 1.8,
    sodium: 44,
  },
  {
    name: 'Греческий йогурт (0%)',
    brand: null,
    kcalPer100g: 59,
    protein: 10,
    fat: 0.4,
    carbs: 3.6,
    fiber: 0,
    sugar: 3.2,
    sodium: 36,
  },
  {
    name: 'Молоко 2.5%',
    brand: null,
    kcalPer100g: 52,
    protein: 2.9,
    fat: 2.5,
    carbs: 4.7,
    fiber: 0,
    sugar: 5,
    sodium: 44,
  },
  {
    name: 'Рис белый (варёный)',
    brand: null,
    kcalPer100g: 130,
    protein: 2.7,
    fat: 0.3,
    carbs: 28,
    fiber: 0.4,
    sugar: 0,
    sodium: 1,
  },
  {
    name: 'Гречка (варёная)',
    brand: null,
    kcalPer100g: 92,
    protein: 3.4,
    fat: 0.6,
    carbs: 20,
    fiber: 1.1,
    sugar: 0,
    sodium: 4,
  },
  {
    name: 'Овсяная каша на воде',
    brand: null,
    kcalPer100g: 68,
    protein: 2.5,
    fat: 1.4,
    carbs: 12,
    fiber: 1.7,
    sugar: 0,
    sodium: 1,
  },
  {
    name: 'Макароны (варёные)',
    brand: null,
    kcalPer100g: 131,
    protein: 5,
    fat: 1.1,
    carbs: 25,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 1,
  },
  {
    name: 'Хлеб цельнозерновой',
    brand: null,
    kcalPer100g: 247,
    protein: 13,
    fat: 4.2,
    carbs: 41,
    fiber: 7,
    sugar: 5,
    sodium: 472,
  },
  {
    name: 'Картофель (варёный)',
    brand: null,
    kcalPer100g: 87,
    protein: 1.9,
    fat: 0.1,
    carbs: 20,
    fiber: 1.8,
    sugar: 0.9,
    sodium: 6,
  },
  {
    name: 'Брокколи (варёная)',
    brand: null,
    kcalPer100g: 35,
    protein: 2.4,
    fat: 0.4,
    carbs: 7.2,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 41,
  },
  {
    name: 'Шпинат (свежий)',
    brand: null,
    kcalPer100g: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
  },
  {
    name: 'Огурец',
    brand: null,
    kcalPer100g: 16,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.6,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 2,
  },
  {
    name: 'Помидор',
    brand: null,
    kcalPer100g: 18,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
  },
  {
    name: 'Банан',
    brand: null,
    kcalPer100g: 89,
    protein: 1.1,
    fat: 0.3,
    carbs: 23,
    fiber: 2.6,
    sugar: 12,
    sodium: 1,
  },
  {
    name: 'Яблоко',
    brand: null,
    kcalPer100g: 52,
    protein: 0.3,
    fat: 0.2,
    carbs: 14,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
  },
  {
    name: 'Апельсин',
    brand: null,
    kcalPer100g: 47,
    protein: 0.9,
    fat: 0.1,
    carbs: 12,
    fiber: 2.4,
    sugar: 9.4,
    sodium: 0,
  },
  {
    name: 'Арахисовое масло (натуральное)',
    brand: null,
    kcalPer100g: 588,
    protein: 25,
    fat: 50,
    carbs: 20,
    fiber: 6,
    sugar: 9,
    sodium: 17,
  },
  {
    name: 'Миндаль',
    brand: null,
    kcalPer100g: 579,
    protein: 21,
    fat: 50,
    carbs: 22,
    fiber: 13,
    sugar: 4.4,
    sodium: 1,
  },
  {
    name: 'Грецкий орех',
    brand: null,
    kcalPer100g: 654,
    protein: 15,
    fat: 65,
    carbs: 14,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 2,
  },
  {
    name: 'Оливковое масло',
    brand: null,
    kcalPer100g: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 2,
  },
  {
    name: 'Масло сливочное',
    brand: null,
    kcalPer100g: 717,
    protein: 0.9,
    fat: 81,
    carbs: 0.1,
    fiber: 0,
    sugar: 0.1,
    sodium: 11,
  },
  {
    name: 'Протеин сывороточный (без вкуса)',
    brand: null,
    kcalPer100g: 370,
    protein: 80,
    fat: 4,
    carbs: 6,
    fiber: 0,
    sugar: 1,
    sodium: 150,
  },
] as const

export async function seedProducts(): Promise<void> {
  const existing = await db.select().from(products).limit(1)
  if (existing.length > 0) return

  const ts = now()
  const rows = SEED_PRODUCTS.map((p) => ({
    id: generateId(),
    ...p,
    brand: p.brand,
    barcode: null,
    source: 'local' as const,
    fiber: p.fiber,
    sugar: p.sugar,
    sodium: p.sodium,
    createdAt: ts,
    updatedAt: ts,
  }))

  await db.insert(products).values(rows)
}
